
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED'
} as const

export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus]


export const LanguageLevel = {
  BEGINNER: 'BEGINNER',
  ELEMENTARY: 'ELEMENTARY',
  INTERMEDIATE: 'INTERMEDIATE',
  UPPER_INTERMEDIATE: 'UPPER_INTERMEDIATE',
  ADVANCED: 'ADVANCED',
  PROFICIENT: 'PROFICIENT'
} as const

export type LanguageLevel = (typeof LanguageLevel)[keyof typeof LanguageLevel]


export const CourseStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
} as const

export type CourseStatus = (typeof CourseStatus)[keyof typeof CourseStatus]


export const LessonType = {
  VIDEO: 'VIDEO',
  TEXT: 'TEXT',
  AUDIO: 'AUDIO',
  INTERACTIVE: 'INTERACTIVE',
  QUIZ: 'QUIZ'
} as const

export type LessonType = (typeof LessonType)[keyof typeof LessonType]


export const EnrollmentStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  DROPPED: 'DROPPED'
} as const

export type EnrollmentStatus = (typeof EnrollmentStatus)[keyof typeof EnrollmentStatus]


export const TestType = {
  PRACTICE: 'PRACTICE',
  FINAL: 'FINAL',
  CERTIFICATION: 'CERTIFICATION'
} as const

export type TestType = (typeof TestType)[keyof typeof TestType]


export const QuestionType = {
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  TRUE_FALSE: 'TRUE_FALSE',
  FILL_BLANK: 'FILL_BLANK',
  MATCHING: 'MATCHING',
  AUDIO_QUESTION: 'AUDIO_QUESTION'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const JobType = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  CONTRACT: 'CONTRACT',
  INTERNSHIP: 'INTERNSHIP'
} as const

export type JobType = (typeof JobType)[keyof typeof JobType]


export const JobStatus = {
  ACTIVE: 'ACTIVE',
  FILLED: 'FILLED',
  CLOSED: 'CLOSED',
  EXPIRED: 'EXPIRED'
} as const

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]


export const ArticleStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
} as const

export type ArticleStatus = (typeof ArticleStatus)[keyof typeof ArticleStatus]


export const SavedItemType = {
  LESSON: 'LESSON',
  ARTICLE: 'ARTICLE',
  JOB: 'JOB'
} as const

export type SavedItemType = (typeof SavedItemType)[keyof typeof SavedItemType]
