
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Course'
export type * from './models/Lesson'
export type * from './models/Enrollment'
export type * from './models/Progress'
export type * from './models/MockTest'
export type * from './models/Question'
export type * from './models/TestAttempt'
export type * from './models/Answer'
export type * from './models/JobListing'
export type * from './models/JobApplication'
export type * from './models/Article'
export type * from './models/Comment'
export type * from './models/SavedItem'
export type * from './models/PageView'
export type * from './commonInputTypes'