
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Course: 'Course',
  Lesson: 'Lesson',
  Enrollment: 'Enrollment',
  Progress: 'Progress',
  MockTest: 'MockTest',
  Question: 'Question',
  TestAttempt: 'TestAttempt',
  Answer: 'Answer',
  JobListing: 'JobListing',
  JobApplication: 'JobApplication',
  Article: 'Article',
  Comment: 'Comment',
  SavedItem: 'SavedItem',
  PageView: 'PageView'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  role: 'role',
  status: 'status',
  googleId: 'googleId',
  emailVerified: 'emailVerified',
  nativeLanguage: 'nativeLanguage',
  learningLanguages: 'learningLanguages',
  timezone: 'timezone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLoginAt: 'lastLoginAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CourseScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  description: 'description',
  language: 'language',
  level: 'level',
  status: 'status',
  thumbnail: 'thumbnail',
  coverImage: 'coverImage',
  duration: 'duration',
  lessonsCount: 'lessonsCount',
  studentsCount: 'studentsCount',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt'
} as const

export type CourseScalarFieldEnum = (typeof CourseScalarFieldEnum)[keyof typeof CourseScalarFieldEnum]


export const LessonScalarFieldEnum = {
  id: 'id',
  courseId: 'courseId',
  slug: 'slug',
  title: 'title',
  description: 'description',
  type: 'type',
  content: 'content',
  videoUrl: 'videoUrl',
  audioUrl: 'audioUrl',
  attachments: 'attachments',
  duration: 'duration',
  order: 'order',
  isFree: 'isFree',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LessonScalarFieldEnum = (typeof LessonScalarFieldEnum)[keyof typeof LessonScalarFieldEnum]


export const EnrollmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  courseId: 'courseId',
  status: 'status',
  completedLessons: 'completedLessons',
  progressPercent: 'progressPercent',
  enrolledAt: 'enrolledAt',
  completedAt: 'completedAt',
  lastAccessedAt: 'lastAccessedAt'
} as const

export type EnrollmentScalarFieldEnum = (typeof EnrollmentScalarFieldEnum)[keyof typeof EnrollmentScalarFieldEnum]


export const ProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  lessonId: 'lessonId',
  completed: 'completed',
  timeSpent: 'timeSpent',
  lastPosition: 'lastPosition',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  updatedAt: 'updatedAt'
} as const

export type ProgressScalarFieldEnum = (typeof ProgressScalarFieldEnum)[keyof typeof ProgressScalarFieldEnum]


export const MockTestScalarFieldEnum = {
  id: 'id',
  courseId: 'courseId',
  title: 'title',
  description: 'description',
  type: 'type',
  duration: 'duration',
  passingScore: 'passingScore',
  questionsCount: 'questionsCount',
  shuffleQuestions: 'shuffleQuestions',
  shuffleOptions: 'shuffleOptions',
  showResults: 'showResults',
  allowRetake: 'allowRetake',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MockTestScalarFieldEnum = (typeof MockTestScalarFieldEnum)[keyof typeof MockTestScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  testId: 'testId',
  type: 'type',
  questionText: 'questionText',
  audioUrl: 'audioUrl',
  imageUrl: 'imageUrl',
  options: 'options',
  correctAnswer: 'correctAnswer',
  points: 'points',
  order: 'order',
  explanation: 'explanation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const TestAttemptScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  testId: 'testId',
  score: 'score',
  correctAnswers: 'correctAnswers',
  totalQuestions: 'totalQuestions',
  passed: 'passed',
  timeSpent: 'timeSpent',
  startedAt: 'startedAt',
  completedAt: 'completedAt'
} as const

export type TestAttemptScalarFieldEnum = (typeof TestAttemptScalarFieldEnum)[keyof typeof TestAttemptScalarFieldEnum]


export const AnswerScalarFieldEnum = {
  id: 'id',
  attemptId: 'attemptId',
  questionId: 'questionId',
  selectedOption: 'selectedOption',
  textAnswer: 'textAnswer',
  isCorrect: 'isCorrect',
  answeredAt: 'answeredAt'
} as const

export type AnswerScalarFieldEnum = (typeof AnswerScalarFieldEnum)[keyof typeof AnswerScalarFieldEnum]


export const JobListingScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  company: 'company',
  location: 'location',
  type: 'type',
  status: 'status',
  description: 'description',
  requirements: 'requirements',
  languageRequired: 'languageRequired',
  languageLevel: 'languageLevel',
  salary: 'salary',
  currency: 'currency',
  applicationUrl: 'applicationUrl',
  email: 'email',
  viewCount: 'viewCount',
  applicationCount: 'applicationCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
} as const

export type JobListingScalarFieldEnum = (typeof JobListingScalarFieldEnum)[keyof typeof JobListingScalarFieldEnum]


export const JobApplicationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  jobId: 'jobId',
  resumeUrl: 'resumeUrl',
  coverLetter: 'coverLetter',
  status: 'status',
  appliedAt: 'appliedAt'
} as const

export type JobApplicationScalarFieldEnum = (typeof JobApplicationScalarFieldEnum)[keyof typeof JobApplicationScalarFieldEnum]


export const ArticleScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  excerpt: 'excerpt',
  content: 'content',
  language: 'language',
  category: 'category',
  tags: 'tags',
  featuredImage: 'featuredImage',
  status: 'status',
  viewCount: 'viewCount',
  readTime: 'readTime',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  authorId: 'authorId',
  authorName: 'authorName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt'
} as const

export type ArticleScalarFieldEnum = (typeof ArticleScalarFieldEnum)[keyof typeof ArticleScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  userId: 'userId',
  content: 'content',
  isApproved: 'isApproved',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const SavedItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemType: 'itemType',
  itemId: 'itemId',
  notes: 'notes',
  savedAt: 'savedAt'
} as const

export type SavedItemScalarFieldEnum = (typeof SavedItemScalarFieldEnum)[keyof typeof SavedItemScalarFieldEnum]


export const PageViewScalarFieldEnum = {
  id: 'id',
  path: 'path',
  referrer: 'referrer',
  userId: 'userId',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  country: 'country',
  viewedAt: 'viewedAt'
} as const

export type PageViewScalarFieldEnum = (typeof PageViewScalarFieldEnum)[keyof typeof PageViewScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  googleId: 'googleId',
  nativeLanguage: 'nativeLanguage',
  learningLanguages: 'learningLanguages',
  timezone: 'timezone'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const CourseOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  description: 'description',
  language: 'language',
  thumbnail: 'thumbnail',
  coverImage: 'coverImage',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription'
} as const

export type CourseOrderByRelevanceFieldEnum = (typeof CourseOrderByRelevanceFieldEnum)[keyof typeof CourseOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const LessonOrderByRelevanceFieldEnum = {
  id: 'id',
  courseId: 'courseId',
  slug: 'slug',
  title: 'title',
  description: 'description',
  content: 'content',
  videoUrl: 'videoUrl',
  audioUrl: 'audioUrl'
} as const

export type LessonOrderByRelevanceFieldEnum = (typeof LessonOrderByRelevanceFieldEnum)[keyof typeof LessonOrderByRelevanceFieldEnum]


export const EnrollmentOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  courseId: 'courseId'
} as const

export type EnrollmentOrderByRelevanceFieldEnum = (typeof EnrollmentOrderByRelevanceFieldEnum)[keyof typeof EnrollmentOrderByRelevanceFieldEnum]


export const ProgressOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  lessonId: 'lessonId'
} as const

export type ProgressOrderByRelevanceFieldEnum = (typeof ProgressOrderByRelevanceFieldEnum)[keyof typeof ProgressOrderByRelevanceFieldEnum]


export const MockTestOrderByRelevanceFieldEnum = {
  id: 'id',
  courseId: 'courseId',
  title: 'title',
  description: 'description'
} as const

export type MockTestOrderByRelevanceFieldEnum = (typeof MockTestOrderByRelevanceFieldEnum)[keyof typeof MockTestOrderByRelevanceFieldEnum]


export const QuestionOrderByRelevanceFieldEnum = {
  id: 'id',
  testId: 'testId',
  questionText: 'questionText',
  audioUrl: 'audioUrl',
  imageUrl: 'imageUrl',
  correctAnswer: 'correctAnswer',
  explanation: 'explanation'
} as const

export type QuestionOrderByRelevanceFieldEnum = (typeof QuestionOrderByRelevanceFieldEnum)[keyof typeof QuestionOrderByRelevanceFieldEnum]


export const TestAttemptOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  testId: 'testId'
} as const

export type TestAttemptOrderByRelevanceFieldEnum = (typeof TestAttemptOrderByRelevanceFieldEnum)[keyof typeof TestAttemptOrderByRelevanceFieldEnum]


export const AnswerOrderByRelevanceFieldEnum = {
  id: 'id',
  attemptId: 'attemptId',
  questionId: 'questionId',
  selectedOption: 'selectedOption',
  textAnswer: 'textAnswer'
} as const

export type AnswerOrderByRelevanceFieldEnum = (typeof AnswerOrderByRelevanceFieldEnum)[keyof typeof AnswerOrderByRelevanceFieldEnum]


export const JobListingOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  company: 'company',
  location: 'location',
  description: 'description',
  requirements: 'requirements',
  languageRequired: 'languageRequired',
  salary: 'salary',
  currency: 'currency',
  applicationUrl: 'applicationUrl',
  email: 'email'
} as const

export type JobListingOrderByRelevanceFieldEnum = (typeof JobListingOrderByRelevanceFieldEnum)[keyof typeof JobListingOrderByRelevanceFieldEnum]


export const JobApplicationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  jobId: 'jobId',
  resumeUrl: 'resumeUrl',
  coverLetter: 'coverLetter',
  status: 'status'
} as const

export type JobApplicationOrderByRelevanceFieldEnum = (typeof JobApplicationOrderByRelevanceFieldEnum)[keyof typeof JobApplicationOrderByRelevanceFieldEnum]


export const ArticleOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  excerpt: 'excerpt',
  content: 'content',
  language: 'language',
  category: 'category',
  tags: 'tags',
  featuredImage: 'featuredImage',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  authorId: 'authorId',
  authorName: 'authorName'
} as const

export type ArticleOrderByRelevanceFieldEnum = (typeof ArticleOrderByRelevanceFieldEnum)[keyof typeof ArticleOrderByRelevanceFieldEnum]


export const CommentOrderByRelevanceFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  userId: 'userId',
  content: 'content'
} as const

export type CommentOrderByRelevanceFieldEnum = (typeof CommentOrderByRelevanceFieldEnum)[keyof typeof CommentOrderByRelevanceFieldEnum]


export const SavedItemOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemId: 'itemId',
  notes: 'notes'
} as const

export type SavedItemOrderByRelevanceFieldEnum = (typeof SavedItemOrderByRelevanceFieldEnum)[keyof typeof SavedItemOrderByRelevanceFieldEnum]


export const PageViewOrderByRelevanceFieldEnum = {
  id: 'id',
  path: 'path',
  referrer: 'referrer',
  userId: 'userId',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  country: 'country'
} as const

export type PageViewOrderByRelevanceFieldEnum = (typeof PageViewOrderByRelevanceFieldEnum)[keyof typeof PageViewOrderByRelevanceFieldEnum]

