import { PrismaClient } from "../src/generated/prisma/client"
import "dotenv/config"
import { cacheHelpers } from "../src/lib/cache"

// Use the same Accelerate connection as the app so seeded data
// appears in the same database the app reads from.
const accelerateUrl = process.env.DATABASE_URL
if (!accelerateUrl) {
  throw new Error('DATABASE_URL environment variable is not set')
}

const prisma = new PrismaClient({
  accelerateUrl,
})

async function main() {
  console.log("🌱 Seeding JLPT N5 mock tests")

  // ============================================================
  // 1. JLPT N5 Vocabulary Test
  // ============================================================
  const jlptN5Vocabulary = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Vocabulary Test 1",
      description: "Basic Japanese vocabulary practice for JLPT N5.",
      language: "Japanese",
      module: "JLPT",
      section: "Vocabulary",
      standardSection: "N5",
      type: "PRACTICE",
      duration: 20,
      passingScore: 60,
      questionsCount: 10,

      questions: {
        create: [
          {
            type: "MULTIPLE_CHOICE",
            questionText: "犬 (いぬ) means?",
            options: ["Dog", "Cat", "Bird", "Fish"],
            correctAnswer: "Dog",
            explanation: "犬 (いぬ) means Dog.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "猫 (ねこ) means?",
            options: ["Dog", "Bird", "Cat", "Horse"],
            correctAnswer: "Cat",
            explanation: "猫 means Cat.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "学校 (がっこう) means?",
            options: ["Hospital", "School", "Office", "Station"],
            correctAnswer: "School",
            explanation: "学校 means School.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "先生 (せんせい) means?",
            options: ["Student", "Teacher", "Doctor", "Friend"],
            correctAnswer: "Teacher",
            explanation: "先生 means Teacher.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "水 (みず) means?",
            options: ["Tea", "Milk", "Water", "Coffee"],
            correctAnswer: "Water",
            explanation: "水 means Water.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "本 (ほん) means?",
            options: ["Pen", "Notebook", "Book", "Bag"],
            correctAnswer: "Book",
            explanation: "本 means Book.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "山 (やま) means?",
            options: ["Mountain", "River", "Sea", "Lake"],
            correctAnswer: "Mountain",
            explanation: "山 means Mountain.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "車 (くるま) means?",
            options: ["Train", "Car", "Bus", "Bicycle"],
            correctAnswer: "Car",
            explanation: "車 means Car.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "友達 (ともだち) means?",
            options: ["Teacher", "Friend", "Parent", "Brother"],
            correctAnswer: "Friend",
            explanation: "友達 means Friend.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "食べる (たべる) means?",
            options: ["Drink", "Run", "Eat", "Sleep"],
            correctAnswer: "Eat",
            explanation: "食べる means Eat.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Vocabulary Test seeded.")

  // ============================================================
  // 2. JLPT N5 Kanji Test
  // ============================================================
  const jlptN5Kanji = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Kanji Test 1",
      description: "Basic Japanese kanji reading practice for JLPT N5.",
      language: "Japanese",
      module: "JLPT",
      section: "Kanji",
      standardSection: "N5",
      type: "PRACTICE",
      duration: 20,
      passingScore: 60,
      questionsCount: 10,

      questions: {
        create: [
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 日 (as in 日曜日)?",
            options: ["にち", "ひ", "か", "び"],
            correctAnswer: "にち",
            explanation: "日 can be read as にち (nichi), ひ (hi), or か (ka) depending on context. In 日曜日 it's にち.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 月 (as in 月曜日)?",
            options: ["つき", "げつ", "がつ", "つく"],
            correctAnswer: "げつ",
            explanation: "月 is read as げつ (getsu) in 月曜日 (Monday). It can also be つき (tsuki) for moon/month.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 火 (as in 火曜日)?",
            options: ["ひ", "か", "び", "ほ"],
            correctAnswer: "か",
            explanation: "火 is read as か (ka) in 火曜日 (Tuesday). It can also be ひ (hi) for fire.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 水 (as in 水曜日)?",
            options: ["みず", "すい", "み", "す"],
            correctAnswer: "すい",
            explanation: "水 is read as すい (sui) in 水曜日 (Wednesday). It can also be みず (mizu) for water.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 木 (as in 木曜日)?",
            options: ["き", "もく", "ぼく", "こ"],
            correctAnswer: "もく",
            explanation: "木 is read as もく (moku) in 木曜日 (Thursday). It can also be き (ki) for tree/wood.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 金 (as in 金曜日)?",
            options: ["かね", "きん", "こん", "かな"],
            correctAnswer: "きん",
            explanation: "金 is read as きん (kin) in 金曜日 (Friday). It can also be かね (kane) for money/gold.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 土 (as in 土曜日)?",
            options: ["つち", "ど", "と", "つ"],
            correctAnswer: "ど",
            explanation: "土 is read as ど (do) in 土曜日 (Saturday). It can also be つち (tsuchi) for soil/earth.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 人 (ひと)?",
            options: ["じん", "にん", "ひと", "と"],
            correctAnswer: "ひと",
            explanation: "人 is read as ひと (hito) when standing alone meaning person. It's read as じん (jin) or にん (nin) in compounds.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 上 (うえ)?",
            options: ["した", "うえ", "なか", "そと"],
            correctAnswer: "うえ",
            explanation: "上 is read as うえ (ue) meaning up/above. 下 (した) means down/below.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 下 (した)?",
            options: ["うえ", "した", "みぎ", "ひだり"],
            correctAnswer: "した",
            explanation: "下 is read as した (shita) meaning down/below. 上 (うえ) means up/above.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Kanji Test seeded.")

  // ============================================================
  // 3. JLPT N5 Grammar Test
  // ============================================================
  const jlptN5Grammar = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Grammar Test 1",
      description: "Basic Japanese grammar practice for JLPT N5.",
      language: "Japanese",
      module: "JLPT",
      section: "Grammar",
      standardSection: "N5",
      type: "PRACTICE",
      duration: 25,
      passingScore: 60,
      questionsCount: 10,

      questions: {
        create: [
          {
            type: "MULTIPLE_CHOICE",
            questionText: "私は学生＿＿＿。",
            options: ["です", "ます", "でした", "ません"],
            correctAnswer: "です",
            explanation: "です is the copula used to state 'is/am/are'. 私は学生です = I am a student.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "これは何＿＿＿か。",
            options: ["を", "に", "で", "です"],
            correctAnswer: "です",
            explanation: "これは何ですか = What is this? The copula です is used at the end of the sentence.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "毎朝コーヒー＿＿＿飲みます。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "を",
            explanation: "を marks the direct object of a verb. コーヒーを飲みます = drink coffee.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "学校＿＿＿行きます。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "に",
            explanation: "に marks the destination of movement. 学校に行きます = go to school.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "日本語＿＿＿話します。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "を",
            explanation: "を marks the object of the verb 話します (speak). 日本語を話します = speak Japanese.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "昨日、映画＿＿＿見ました。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "を",
            explanation: "を marks the direct object. 映画を見ました = watched a movie.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "これは私＿＿＿本です。",
            options: ["の", "を", "に", "で"],
            correctAnswer: "の",
            explanation: "の shows possession. 私の本 = my book.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "田中さんは今、家＿＿＿います。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "に",
            explanation: "に is used with います (to exist) to indicate location. 家にいます = is at home.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "私は毎日学校＿＿＿行きます。",
            options: ["へ", "を", "が", "で"],
            correctAnswer: "へ",
            explanation: "へ marks direction/destination. 学校へ行きます = go to school. Both へ and に can be used for destination.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "この本は面白い＿＿＿。",
            options: ["です", "ます", "でした", "ません"],
            correctAnswer: "です",
            explanation: "です is used after adjectives to make a polite statement. 面白いです = is interesting.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Grammar Test seeded.")

  // ============================================================
  // 4. JLPT N5 Reading Test
  // ============================================================
  const jlptN5Reading = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Reading Test 1",
      description: "Basic Japanese reading comprehension practice for JLPT N5.",
      language: "Japanese",
      module: "JLPT",
      section: "Reading",
      standardSection: "N5",
      type: "READING",
      duration: 30,
      passingScore: 60,
      questionsCount: 10,

      questions: {
        create: [
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎朝七時に起きます。それから、朝ごはんを食べます。八時に家を出ます。学校に九時に行きます。\n\nQuestion: 私は毎朝何時に起きますか。",
            options: ["六時", "七時", "八時", "九時"],
            correctAnswer: "七時",
            explanation: "The passage says 毎朝七時に起きます = I wake up at 7 every morning.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎朝七時に起きます。それから、朝ごはんを食べます。八時に家を出ます。学校に九時に行きます。\n\nQuestion: 私は何時に家を出ますか。",
            options: ["七時", "八時", "九時", "十時"],
            correctAnswer: "八時",
            explanation: "The passage says 八時に家を出ます = I leave home at 8.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 昨日は日曜日でした。私は友達と公園に行きました。公園でサッカーをしました。とても楽しかったです。\n\nQuestion: 昨日は何曜日でしたか。",
            options: ["土曜日", "日曜日", "月曜日", "金曜日"],
            correctAnswer: "日曜日",
            explanation: "The passage says 昨日は日曜日でした = Yesterday was Sunday.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 昨日は日曜日でした。私は友達と公園に行きました。公園でサッカーをしました。とても楽しかったです。\n\nQuestion: 昨日、私はどこに行きましたか。",
            options: ["学校", "映画館", "公園", "レストラン"],
            correctAnswer: "公園",
            explanation: "The passage says 友達と公園に行きました = I went to the park with my friend.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私の家族は四人です。父と母と姉と私です。父は会社員です。母は看護師です。姉は大学生です。\n\nQuestion: 私の家族は何人ですか。",
            options: ["三人", "四人", "五人", "六人"],
            correctAnswer: "四人",
            explanation: "The passage says 私の家族は四人です = My family has 4 people.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私の家族は四人です。父と母と姉と私です。父は会社員です。母は看護師です。姉は大学生です。\n\nQuestion: 父の仕事は何ですか。",
            options: ["看護師", "先生", "会社員", "大学生"],
            correctAnswer: "会社員",
            explanation: "The passage says 父は会社員です = My father is a company employee.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 今日はいい天気です。空は青いです。私は窓を開けました。風が気持ちいいです。\n\nQuestion: 今日の天気はどうですか。",
            options: ["悪いです", "いいです", "寒いです", "暑いです"],
            correctAnswer: "いいです",
            explanation: "The passage says 今日はいい天気です = Today is good weather.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 今日はいい天気です。空は青いです。私は窓を開けました。風が気持ちいいです。\n\nQuestion: 私は何を開けましたか。",
            options: ["ドア", "窓", "本", "箱"],
            correctAnswer: "窓",
            explanation: "The passage says 私は窓を開けました = I opened the window.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎日電車で学校に行きます。電車はとても混みます。でも、学校は楽しいです。\n\nQuestion: 私は何で学校に行きますか。",
            options: ["バス", "車", "電車", "自転車"],
            correctAnswer: "電車",
            explanation: "The passage says 毎日電車で学校に行きます = I go to school by train every day.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎日電車で学校に行きます。電車はとても混みます。でも、学校は楽しいです。\n\nQuestion: 電車はどうですか。",
            options: ["空いています", "混みます", "速いです", "遅いです"],
            correctAnswer: "混みます",
            explanation: "The passage says 電車はとても混みます = The train is very crowded.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Reading Test seeded.")

  // ============================================================
  // 5. JLPT N5 Listening Test
  // ============================================================
  const jlptN5Listening = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Listening Test 1",
      description: "Basic Japanese listening comprehension practice for JLPT N5.",
      language: "Japanese",
      module: "JLPT",
      section: "Listening",
      standardSection: "N5",
      type: "LISTENING",
      duration: 25,
      passingScore: 60,
      questionsCount: 10,

      questions: {
        create: [
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「私は毎朝六時に起きます。それから、ジョギングをします。」\n\nQuestion: 女の人は毎朝何時に起きますか。",
            options: ["五時", "六時", "七時", "八時"],
            correctAnswer: "六時",
            explanation: "The woman says 毎朝六時に起きます = I wake up at 6 every morning.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私はコーヒーが好きです。でも、お茶も好きです。」\n\nQuestion: 男の人は何が好きですか。",
            options: ["コーヒーだけ", "お茶だけ", "コーヒーとお茶", "水だけ"],
            correctAnswer: "コーヒーとお茶",
            explanation: "The man says he likes coffee, but he also likes tea. So he likes both.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「明日は雨が降ります。傘を持って行ってください。」\n\nQuestion: 明日の天気はどうですか。",
            options: ["晴れ", "雨", "雪", "曇り"],
            correctAnswer: "雨",
            explanation: "The woman says 明日は雨が降ります = It will rain tomorrow.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私は毎日日本語を勉強します。日本語は難しいですが、楽しいです。」\n\nQuestion: 男の人は毎日何を勉強しますか。",
            options: ["英語", "日本語", "中国語", "韓国語"],
            correctAnswer: "日本語",
            explanation: "The man says 毎日日本語を勉強します = I study Japanese every day.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「私は魚が好きです。でも、肉はあまり好きじゃありません。」\n\nQuestion: 女の人は何が好きですか。",
            options: ["肉", "魚", "野菜", "果物"],
            correctAnswer: "魚",
            explanation: "The woman says 私は魚が好きです = I like fish. She doesn't like meat much.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私は日曜日に友達と映画を見に行きます。」\n\nQuestion: 男の人はいつ映画を見に行きますか。",
            options: ["土曜日", "日曜日", "月曜日", "金曜日"],
            correctAnswer: "日曜日",
            explanation: "The man says 日曜日に友達と映画を見に行きます = I will go to see a movie with my friend on Sunday.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「私は今、銀行で働いています。銀行は駅の近くにあります。」\n\nQuestion: 女の人はどこで働いていますか。",
            options: ["学校", "病院", "銀行", "会社"],
            correctAnswer: "銀行",
            explanation: "The woman says 私は今、銀行で働いています = I work at a bank now.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私は毎晩十一時に寝ます。朝は七時に起きます。」\n\nQuestion: 男の人は毎晩何時に寝ますか。",
            options: ["十時", "十一時", "十二時", "九時"],
            correctAnswer: "十一時",
            explanation: "The man says 毎晩十一時に寝ます = I go to bed at 11 every night.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「私は週末に買い物に行きます。スーパーで野菜と果物を買います。」\n\nQuestion: 女の人はどこで買い物をしますか。",
            options: ["デパート", "コンビニ", "スーパー", "本屋"],
            correctAnswer: "スーパー",
            explanation: "The woman says スーパーで野菜と果物を買います = I buy vegetables and fruits at the supermarket.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私は来月、日本へ行きます。飛行機で行きます。」\n\nQuestion: 男の人は何で日本へ行きますか。",
            options: ["船", "電車", "飛行機", "バス"],
            correctAnswer: "飛行機",
            explanation: "The man says 飛行機で行きます = I will go by airplane.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Listening Test seeded.")

  // ============================================================
  // 6. JLPT N5 Full Mock Test (Comprehensive - all sections)
  // ============================================================
  const jlptN5FullTest = await prisma.mockTest.create({
    data: {
      title: "JLPT N5 Full Mock Test",
      description: "Complete JLPT N5 mock test covering Vocabulary, Kanji, Grammar, Reading, and Listening sections.",
      language: "Japanese",
      module: "JLPT",
      section: "Full Test",
      standardSection: "N5",
      type: "FINAL",
      duration: 105,
      passingScore: 60,
      questionsCount: 20,

      questions: {
        create: [
          // --- Vocabulary Section ---
          {
            type: "MULTIPLE_CHOICE",
            questionText: "時間 (じかん) means?",
            options: ["Money", "Time", "Place", "Person"],
            correctAnswer: "Time",
            explanation: "時間 (じかん) means time.",
            order: 1,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "安い (やすい) means?",
            options: ["Expensive", "Cheap", "Big", "Small"],
            correctAnswer: "Cheap",
            explanation: "安い (やすい) means cheap. 高い (たかい) means expensive.",
            order: 2,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "新しい (あたらしい) means?",
            options: ["Old", "New", "Good", "Bad"],
            correctAnswer: "New",
            explanation: "新しい (あたらしい) means new. 古い (ふるい) means old.",
            order: 3,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "大きい (おおきい) means?",
            options: ["Small", "Big", "Long", "Short"],
            correctAnswer: "Big",
            explanation: "大きい (おおきい) means big. 小さい (ちいさい) means small.",
            order: 4,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "買います (かいます) means?",
            options: ["Sell", "Buy", "Give", "Take"],
            correctAnswer: "Buy",
            explanation: "買います (かいます) means to buy. 売ります (うります) means to sell.",
            order: 5,
            language: "Japanese",
            module: "JLPT",
            section: "Vocabulary",
            standardSection: "N5",
            difficulty: "Easy",
          },

          // --- Kanji Section ---
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 天気 (てんき)?",
            options: ["てんき", "てんけ", "でんき", "てき"],
            correctAnswer: "てんき",
            explanation: "天気 (てんき) means weather.",
            order: 6,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 電車 (でんしゃ)?",
            options: ["でんしゃ", "でんし", "てんしゃ", "でんちゃ"],
            correctAnswer: "でんしゃ",
            explanation: "電車 (でんしゃ) means train.",
            order: 7,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 名前 (なまえ)?",
            options: ["なまえ", "なめ", "まえ", "なま"],
            correctAnswer: "なまえ",
            explanation: "名前 (なまえ) means name.",
            order: 8,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 外国 (がいこく)?",
            options: ["がいこく", "がいこ", "そとこく", "がいごく"],
            correctAnswer: "がいこく",
            explanation: "外国 (がいこく) means foreign country.",
            order: 9,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "How do you read 会社 (かいしゃ)?",
            options: ["かいしゃ", "かいし", "がいしゃ", "かいじゃ"],
            correctAnswer: "かいしゃ",
            explanation: "会社 (かいしゃ) means company.",
            order: 10,
            language: "Japanese",
            module: "JLPT",
            section: "Kanji",
            standardSection: "N5",
            difficulty: "Easy",
          },

          // --- Grammar Section ---
          {
            type: "MULTIPLE_CHOICE",
            questionText: "私は毎日日本語＿＿＿勉強します。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "を",
            explanation: "を marks the direct object. 日本語を勉強します = study Japanese.",
            order: 11,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "昨日、友達＿＿＿会いました。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "に",
            explanation: "に is used with 会います (to meet). 友達に会いました = met a friend.",
            order: 12,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "このレストランは有名＿＿＿。",
            options: ["です", "ます", "でした", "ません"],
            correctAnswer: "です",
            explanation: "です is used after な-adjectives. 有名です = is famous.",
            order: 13,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "私は日本＿＿＿行きたいです。",
            options: ["を", "が", "に", "で"],
            correctAnswer: "に",
            explanation: "に marks the destination with 行きたい (want to go). 日本に行きたいです = want to go to Japan.",
            order: 14,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "MULTIPLE_CHOICE",
            questionText: "これは私の本です。＿＿＿はあなたのです。",
            options: ["これ", "それ", "あれ", "どれ"],
            correctAnswer: "それ",
            explanation: "それ refers to something near the listener. これは私の本です。それはあなたのです = This is my book. That is yours.",
            order: 15,
            language: "Japanese",
            module: "JLPT",
            section: "Grammar",
            standardSection: "N5",
            difficulty: "Easy",
          },

          // --- Reading Section ---
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎日六時に起きます。朝ごはんを食べて、七時に家を出ます。会社に八時に着きます。\n\nQuestion: 私は何時に会社に着きますか。",
            options: ["六時", "七時", "八時", "九時"],
            correctAnswer: "八時",
            explanation: "The passage says 会社に八時に着きます = I arrive at the company at 8.",
            order: 16,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私は毎日六時に起きます。朝ごはんを食べて、七時に家を出ます。会社に八時に着きます。\n\nQuestion: 私は何時に家を出ますか。",
            options: ["六時", "七時", "八時", "九時"],
            correctAnswer: "七時",
            explanation: "The passage says 七時に家を出ます = I leave home at 7.",
            order: 17,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "READING_COMPREHENSION",
            questionText: "Passage: 私の趣味は写真を撮ることです。週末に公園や山で写真を撮ります。\n\nQuestion: 私の趣味は何ですか。",
            options: ["料理", "写真を撮ること", "音楽", "スポーツ"],
            correctAnswer: "写真を撮ること",
            explanation: "The passage says 私の趣味は写真を撮ることです = My hobby is taking photos.",
            order: 18,
            language: "Japanese",
            module: "JLPT",
            section: "Reading",
            standardSection: "N5",
            difficulty: "Easy",
          },

          // --- Listening Section ---
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 女の人が話しています。「私は毎週土曜日にスーパーへ行きます。そこで野菜と果物を買います。」\n\nQuestion: 女の人はいつスーパーへ行きますか。",
            options: ["日曜日", "土曜日", "月曜日", "金曜日"],
            correctAnswer: "土曜日",
            explanation: "The woman says 毎週土曜日にスーパーへ行きます = I go to the supermarket every Saturday.",
            order: 19,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
          {
            type: "LISTENING_COMPREHENSION",
            questionText: "Audio: 男の人が話しています。「私は来週、京都へ行きます。京都でお寺を見ます。」\n\nQuestion: 男の人は来週どこへ行きますか。",
            options: ["大阪", "東京", "京都", "北海道"],
            correctAnswer: "京都",
            explanation: "The man says 来週、京都へ行きます = I will go to Kyoto next week.",
            order: 20,
            language: "Japanese",
            module: "JLPT",
            section: "Listening",
            standardSection: "N5",
            difficulty: "Easy",
          },
        ],
      },
    },
  })

  console.log("✅ JLPT N5 Full Mock Test seeded.")

  // Invalidate all mock test caches so the new tests appear immediately
  await cacheHelpers.deletePattern('mock-tests:*');
  await cacheHelpers.deletePattern('admin-mock-tests:*');

  console.log("🎉 All JLPT N5 mock tests seeded successfully!")
  console.log(`   - ${jlptN5Vocabulary.title} (${jlptN5Vocabulary.questionsCount} questions)`)
  console.log(`   - ${jlptN5Kanji.title} (${jlptN5Kanji.questionsCount} questions)`)
  console.log(`   - ${jlptN5Grammar.title} (${jlptN5Grammar.questionsCount} questions)`)
  console.log(`   - ${jlptN5Reading.title} (${jlptN5Reading.questionsCount} questions)`)
  console.log(`   - ${jlptN5Listening.title} (${jlptN5Listening.questionsCount} questions)`)
  console.log(`   - ${jlptN5FullTest.title} (${jlptN5FullTest.questionsCount} questions)`)
  console.log("🧹 Cache invalidated for mock-tests")
}

main()
  .catch((error) => {
    console.error("❌ Seed failed:", error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })