
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Course` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Course
 * 
 */
export type CourseModel = runtime.Types.Result.DefaultSelection<Prisma.$CoursePayload>

export type AggregateCourse = {
  _count: CourseCountAggregateOutputType | null
  _avg: CourseAvgAggregateOutputType | null
  _sum: CourseSumAggregateOutputType | null
  _min: CourseMinAggregateOutputType | null
  _max: CourseMaxAggregateOutputType | null
}

export type CourseAvgAggregateOutputType = {
  duration: number | null
  lessonsCount: number | null
  studentsCount: number | null
  order: number | null
}

export type CourseSumAggregateOutputType = {
  duration: number | null
  lessonsCount: number | null
  studentsCount: number | null
  order: number | null
}

export type CourseMinAggregateOutputType = {
  id: string | null
  slug: string | null
  title: string | null
  description: string | null
  language: string | null
  level: $Enums.LanguageLevel | null
  status: $Enums.CourseStatus | null
  thumbnail: string | null
  coverImage: string | null
  duration: number | null
  lessonsCount: number | null
  studentsCount: number | null
  metaTitle: string | null
  metaDescription: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
  publishedAt: Date | null
}

export type CourseMaxAggregateOutputType = {
  id: string | null
  slug: string | null
  title: string | null
  description: string | null
  language: string | null
  level: $Enums.LanguageLevel | null
  status: $Enums.CourseStatus | null
  thumbnail: string | null
  coverImage: string | null
  duration: number | null
  lessonsCount: number | null
  studentsCount: number | null
  metaTitle: string | null
  metaDescription: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
  publishedAt: Date | null
}

export type CourseCountAggregateOutputType = {
  id: number
  slug: number
  title: number
  description: number
  language: number
  level: number
  status: number
  thumbnail: number
  coverImage: number
  duration: number
  lessonsCount: number
  studentsCount: number
  metaTitle: number
  metaDescription: number
  order: number
  createdAt: number
  updatedAt: number
  publishedAt: number
  _all: number
}


export type CourseAvgAggregateInputType = {
  duration?: true
  lessonsCount?: true
  studentsCount?: true
  order?: true
}

export type CourseSumAggregateInputType = {
  duration?: true
  lessonsCount?: true
  studentsCount?: true
  order?: true
}

export type CourseMinAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  description?: true
  language?: true
  level?: true
  status?: true
  thumbnail?: true
  coverImage?: true
  duration?: true
  lessonsCount?: true
  studentsCount?: true
  metaTitle?: true
  metaDescription?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
}

export type CourseMaxAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  description?: true
  language?: true
  level?: true
  status?: true
  thumbnail?: true
  coverImage?: true
  duration?: true
  lessonsCount?: true
  studentsCount?: true
  metaTitle?: true
  metaDescription?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
}

export type CourseCountAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  description?: true
  language?: true
  level?: true
  status?: true
  thumbnail?: true
  coverImage?: true
  duration?: true
  lessonsCount?: true
  studentsCount?: true
  metaTitle?: true
  metaDescription?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
  _all?: true
}

export type CourseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Course to aggregate.
   */
  where?: Prisma.CourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courses to fetch.
   */
  orderBy?: Prisma.CourseOrderByWithRelationInput | Prisma.CourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Courses
  **/
  _count?: true | CourseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CourseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CourseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CourseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CourseMaxAggregateInputType
}

export type GetCourseAggregateType<T extends CourseAggregateArgs> = {
      [P in keyof T & keyof AggregateCourse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourse[P]>
    : Prisma.GetScalarType<T[P], AggregateCourse[P]>
}




export type CourseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CourseWhereInput
  orderBy?: Prisma.CourseOrderByWithAggregationInput | Prisma.CourseOrderByWithAggregationInput[]
  by: Prisma.CourseScalarFieldEnum[] | Prisma.CourseScalarFieldEnum
  having?: Prisma.CourseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CourseCountAggregateInputType | true
  _avg?: CourseAvgAggregateInputType
  _sum?: CourseSumAggregateInputType
  _min?: CourseMinAggregateInputType
  _max?: CourseMaxAggregateInputType
}

export type CourseGroupByOutputType = {
  id: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status: $Enums.CourseStatus
  thumbnail: string | null
  coverImage: string | null
  duration: number | null
  lessonsCount: number
  studentsCount: number
  metaTitle: string | null
  metaDescription: string | null
  order: number
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  _count: CourseCountAggregateOutputType | null
  _avg: CourseAvgAggregateOutputType | null
  _sum: CourseSumAggregateOutputType | null
  _min: CourseMinAggregateOutputType | null
  _max: CourseMaxAggregateOutputType | null
}

type GetCourseGroupByPayload<T extends CourseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CourseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CourseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CourseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CourseGroupByOutputType[P]>
      }
    >
  >



export type CourseWhereInput = {
  AND?: Prisma.CourseWhereInput | Prisma.CourseWhereInput[]
  OR?: Prisma.CourseWhereInput[]
  NOT?: Prisma.CourseWhereInput | Prisma.CourseWhereInput[]
  id?: Prisma.StringFilter<"Course"> | string
  slug?: Prisma.StringFilter<"Course"> | string
  title?: Prisma.StringFilter<"Course"> | string
  description?: Prisma.StringFilter<"Course"> | string
  language?: Prisma.StringFilter<"Course"> | string
  level?: Prisma.EnumLanguageLevelFilter<"Course"> | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFilter<"Course"> | $Enums.CourseStatus
  thumbnail?: Prisma.StringNullableFilter<"Course"> | string | null
  coverImage?: Prisma.StringNullableFilter<"Course"> | string | null
  duration?: Prisma.IntNullableFilter<"Course"> | number | null
  lessonsCount?: Prisma.IntFilter<"Course"> | number
  studentsCount?: Prisma.IntFilter<"Course"> | number
  metaTitle?: Prisma.StringNullableFilter<"Course"> | string | null
  metaDescription?: Prisma.StringNullableFilter<"Course"> | string | null
  order?: Prisma.IntFilter<"Course"> | number
  createdAt?: Prisma.DateTimeFilter<"Course"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Course"> | Date | string
  publishedAt?: Prisma.DateTimeNullableFilter<"Course"> | Date | string | null
  lessons?: Prisma.LessonListRelationFilter
  enrollments?: Prisma.EnrollmentListRelationFilter
  mockTests?: Prisma.MockTestListRelationFilter
}

export type CourseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  level?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrderInput | Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  metaDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lessons?: Prisma.LessonOrderByRelationAggregateInput
  enrollments?: Prisma.EnrollmentOrderByRelationAggregateInput
  mockTests?: Prisma.MockTestOrderByRelationAggregateInput
  _relevance?: Prisma.CourseOrderByRelevanceInput
}

export type CourseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.CourseWhereInput | Prisma.CourseWhereInput[]
  OR?: Prisma.CourseWhereInput[]
  NOT?: Prisma.CourseWhereInput | Prisma.CourseWhereInput[]
  title?: Prisma.StringFilter<"Course"> | string
  description?: Prisma.StringFilter<"Course"> | string
  language?: Prisma.StringFilter<"Course"> | string
  level?: Prisma.EnumLanguageLevelFilter<"Course"> | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFilter<"Course"> | $Enums.CourseStatus
  thumbnail?: Prisma.StringNullableFilter<"Course"> | string | null
  coverImage?: Prisma.StringNullableFilter<"Course"> | string | null
  duration?: Prisma.IntNullableFilter<"Course"> | number | null
  lessonsCount?: Prisma.IntFilter<"Course"> | number
  studentsCount?: Prisma.IntFilter<"Course"> | number
  metaTitle?: Prisma.StringNullableFilter<"Course"> | string | null
  metaDescription?: Prisma.StringNullableFilter<"Course"> | string | null
  order?: Prisma.IntFilter<"Course"> | number
  createdAt?: Prisma.DateTimeFilter<"Course"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Course"> | Date | string
  publishedAt?: Prisma.DateTimeNullableFilter<"Course"> | Date | string | null
  lessons?: Prisma.LessonListRelationFilter
  enrollments?: Prisma.EnrollmentListRelationFilter
  mockTests?: Prisma.MockTestListRelationFilter
}, "id" | "slug">

export type CourseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  level?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrderInput | Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  metaDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CourseCountOrderByAggregateInput
  _avg?: Prisma.CourseAvgOrderByAggregateInput
  _max?: Prisma.CourseMaxOrderByAggregateInput
  _min?: Prisma.CourseMinOrderByAggregateInput
  _sum?: Prisma.CourseSumOrderByAggregateInput
}

export type CourseScalarWhereWithAggregatesInput = {
  AND?: Prisma.CourseScalarWhereWithAggregatesInput | Prisma.CourseScalarWhereWithAggregatesInput[]
  OR?: Prisma.CourseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CourseScalarWhereWithAggregatesInput | Prisma.CourseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Course"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Course"> | string
  title?: Prisma.StringWithAggregatesFilter<"Course"> | string
  description?: Prisma.StringWithAggregatesFilter<"Course"> | string
  language?: Prisma.StringWithAggregatesFilter<"Course"> | string
  level?: Prisma.EnumLanguageLevelWithAggregatesFilter<"Course"> | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusWithAggregatesFilter<"Course"> | $Enums.CourseStatus
  thumbnail?: Prisma.StringNullableWithAggregatesFilter<"Course"> | string | null
  coverImage?: Prisma.StringNullableWithAggregatesFilter<"Course"> | string | null
  duration?: Prisma.IntNullableWithAggregatesFilter<"Course"> | number | null
  lessonsCount?: Prisma.IntWithAggregatesFilter<"Course"> | number
  studentsCount?: Prisma.IntWithAggregatesFilter<"Course"> | number
  metaTitle?: Prisma.StringNullableWithAggregatesFilter<"Course"> | string | null
  metaDescription?: Prisma.StringNullableWithAggregatesFilter<"Course"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"Course"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Course"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Course"> | Date | string
  publishedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Course"> | Date | string | null
}

export type CourseCreateInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonCreateNestedManyWithoutCourseInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestCreateNestedManyWithoutCourseInput
}

export type CourseUncheckedCreateInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCourseInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestUncheckedCreateNestedManyWithoutCourseInput
}

export type CourseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUpdateManyWithoutCourseNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUpdateManyWithoutCourseNestedInput
}

export type CourseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUncheckedUpdateManyWithoutCourseNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUncheckedUpdateManyWithoutCourseNestedInput
}

export type CourseCreateManyInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
}

export type CourseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CourseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CourseOrderByRelevanceInput = {
  fields: Prisma.CourseOrderByRelevanceFieldEnum | Prisma.CourseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CourseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  level?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
}

export type CourseAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type CourseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  level?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
}

export type CourseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  level?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thumbnail?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
}

export type CourseSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  lessonsCount?: Prisma.SortOrder
  studentsCount?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type CourseScalarRelationFilter = {
  is?: Prisma.CourseWhereInput
  isNot?: Prisma.CourseWhereInput
}

export type CourseNullableScalarRelationFilter = {
  is?: Prisma.CourseWhereInput | null
  isNot?: Prisma.CourseWhereInput | null
}

export type EnumLanguageLevelFieldUpdateOperationsInput = {
  set?: $Enums.LanguageLevel
}

export type EnumCourseStatusFieldUpdateOperationsInput = {
  set?: $Enums.CourseStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CourseCreateNestedOneWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutLessonsInput, Prisma.CourseUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutLessonsInput
  connect?: Prisma.CourseWhereUniqueInput
}

export type CourseUpdateOneRequiredWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutLessonsInput, Prisma.CourseUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutLessonsInput
  upsert?: Prisma.CourseUpsertWithoutLessonsInput
  connect?: Prisma.CourseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourseUpdateToOneWithWhereWithoutLessonsInput, Prisma.CourseUpdateWithoutLessonsInput>, Prisma.CourseUncheckedUpdateWithoutLessonsInput>
}

export type CourseCreateNestedOneWithoutEnrollmentsInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutEnrollmentsInput, Prisma.CourseUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutEnrollmentsInput
  connect?: Prisma.CourseWhereUniqueInput
}

export type CourseUpdateOneRequiredWithoutEnrollmentsNestedInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutEnrollmentsInput, Prisma.CourseUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutEnrollmentsInput
  upsert?: Prisma.CourseUpsertWithoutEnrollmentsInput
  connect?: Prisma.CourseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourseUpdateToOneWithWhereWithoutEnrollmentsInput, Prisma.CourseUpdateWithoutEnrollmentsInput>, Prisma.CourseUncheckedUpdateWithoutEnrollmentsInput>
}

export type CourseCreateNestedOneWithoutMockTestsInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutMockTestsInput, Prisma.CourseUncheckedCreateWithoutMockTestsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutMockTestsInput
  connect?: Prisma.CourseWhereUniqueInput
}

export type CourseUpdateOneWithoutMockTestsNestedInput = {
  create?: Prisma.XOR<Prisma.CourseCreateWithoutMockTestsInput, Prisma.CourseUncheckedCreateWithoutMockTestsInput>
  connectOrCreate?: Prisma.CourseCreateOrConnectWithoutMockTestsInput
  upsert?: Prisma.CourseUpsertWithoutMockTestsInput
  disconnect?: Prisma.CourseWhereInput | boolean
  delete?: Prisma.CourseWhereInput | boolean
  connect?: Prisma.CourseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourseUpdateToOneWithWhereWithoutMockTestsInput, Prisma.CourseUpdateWithoutMockTestsInput>, Prisma.CourseUncheckedUpdateWithoutMockTestsInput>
}

export type CourseCreateWithoutLessonsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestCreateNestedManyWithoutCourseInput
}

export type CourseUncheckedCreateWithoutLessonsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestUncheckedCreateNestedManyWithoutCourseInput
}

export type CourseCreateOrConnectWithoutLessonsInput = {
  where: Prisma.CourseWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseCreateWithoutLessonsInput, Prisma.CourseUncheckedCreateWithoutLessonsInput>
}

export type CourseUpsertWithoutLessonsInput = {
  update: Prisma.XOR<Prisma.CourseUpdateWithoutLessonsInput, Prisma.CourseUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.CourseCreateWithoutLessonsInput, Prisma.CourseUncheckedCreateWithoutLessonsInput>
  where?: Prisma.CourseWhereInput
}

export type CourseUpdateToOneWithWhereWithoutLessonsInput = {
  where?: Prisma.CourseWhereInput
  data: Prisma.XOR<Prisma.CourseUpdateWithoutLessonsInput, Prisma.CourseUncheckedUpdateWithoutLessonsInput>
}

export type CourseUpdateWithoutLessonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  enrollments?: Prisma.EnrollmentUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUpdateManyWithoutCourseNestedInput
}

export type CourseUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUncheckedUpdateManyWithoutCourseNestedInput
}

export type CourseCreateWithoutEnrollmentsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestCreateNestedManyWithoutCourseInput
}

export type CourseUncheckedCreateWithoutEnrollmentsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCourseInput
  mockTests?: Prisma.MockTestUncheckedCreateNestedManyWithoutCourseInput
}

export type CourseCreateOrConnectWithoutEnrollmentsInput = {
  where: Prisma.CourseWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseCreateWithoutEnrollmentsInput, Prisma.CourseUncheckedCreateWithoutEnrollmentsInput>
}

export type CourseUpsertWithoutEnrollmentsInput = {
  update: Prisma.XOR<Prisma.CourseUpdateWithoutEnrollmentsInput, Prisma.CourseUncheckedUpdateWithoutEnrollmentsInput>
  create: Prisma.XOR<Prisma.CourseCreateWithoutEnrollmentsInput, Prisma.CourseUncheckedCreateWithoutEnrollmentsInput>
  where?: Prisma.CourseWhereInput
}

export type CourseUpdateToOneWithWhereWithoutEnrollmentsInput = {
  where?: Prisma.CourseWhereInput
  data: Prisma.XOR<Prisma.CourseUpdateWithoutEnrollmentsInput, Prisma.CourseUncheckedUpdateWithoutEnrollmentsInput>
}

export type CourseUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUpdateManyWithoutCourseNestedInput
}

export type CourseUncheckedUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUncheckedUpdateManyWithoutCourseNestedInput
  mockTests?: Prisma.MockTestUncheckedUpdateManyWithoutCourseNestedInput
}

export type CourseCreateWithoutMockTestsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonCreateNestedManyWithoutCourseInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutCourseInput
}

export type CourseUncheckedCreateWithoutMockTestsInput = {
  id?: string
  slug: string
  title: string
  description: string
  language: string
  level: $Enums.LanguageLevel
  status?: $Enums.CourseStatus
  thumbnail?: string | null
  coverImage?: string | null
  duration?: number | null
  lessonsCount?: number
  studentsCount?: number
  metaTitle?: string | null
  metaDescription?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string | null
  lessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCourseInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutCourseInput
}

export type CourseCreateOrConnectWithoutMockTestsInput = {
  where: Prisma.CourseWhereUniqueInput
  create: Prisma.XOR<Prisma.CourseCreateWithoutMockTestsInput, Prisma.CourseUncheckedCreateWithoutMockTestsInput>
}

export type CourseUpsertWithoutMockTestsInput = {
  update: Prisma.XOR<Prisma.CourseUpdateWithoutMockTestsInput, Prisma.CourseUncheckedUpdateWithoutMockTestsInput>
  create: Prisma.XOR<Prisma.CourseCreateWithoutMockTestsInput, Prisma.CourseUncheckedCreateWithoutMockTestsInput>
  where?: Prisma.CourseWhereInput
}

export type CourseUpdateToOneWithWhereWithoutMockTestsInput = {
  where?: Prisma.CourseWhereInput
  data: Prisma.XOR<Prisma.CourseUpdateWithoutMockTestsInput, Prisma.CourseUncheckedUpdateWithoutMockTestsInput>
}

export type CourseUpdateWithoutMockTestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUpdateManyWithoutCourseNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutCourseNestedInput
}

export type CourseUncheckedUpdateWithoutMockTestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumLanguageLevelFieldUpdateOperationsInput | $Enums.LanguageLevel
  status?: Prisma.EnumCourseStatusFieldUpdateOperationsInput | $Enums.CourseStatus
  thumbnail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessonsCount?: Prisma.IntFieldUpdateOperationsInput | number
  studentsCount?: Prisma.IntFieldUpdateOperationsInput | number
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lessons?: Prisma.LessonUncheckedUpdateManyWithoutCourseNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutCourseNestedInput
}


/**
 * Count Type CourseCountOutputType
 */

export type CourseCountOutputType = {
  lessons: number
  enrollments: number
  mockTests: number
}

export type CourseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | CourseCountOutputTypeCountLessonsArgs
  enrollments?: boolean | CourseCountOutputTypeCountEnrollmentsArgs
  mockTests?: boolean | CourseCountOutputTypeCountMockTestsArgs
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseCountOutputType
   */
  select?: Prisma.CourseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountLessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LessonWhereInput
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountEnrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EnrollmentWhereInput
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountMockTestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MockTestWhereInput
}


export type CourseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  description?: boolean
  language?: boolean
  level?: boolean
  status?: boolean
  thumbnail?: boolean
  coverImage?: boolean
  duration?: boolean
  lessonsCount?: boolean
  studentsCount?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
  lessons?: boolean | Prisma.Course$lessonsArgs<ExtArgs>
  enrollments?: boolean | Prisma.Course$enrollmentsArgs<ExtArgs>
  mockTests?: boolean | Prisma.Course$mockTestsArgs<ExtArgs>
  _count?: boolean | Prisma.CourseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["course"]>

export type CourseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  description?: boolean
  language?: boolean
  level?: boolean
  status?: boolean
  thumbnail?: boolean
  coverImage?: boolean
  duration?: boolean
  lessonsCount?: boolean
  studentsCount?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
}, ExtArgs["result"]["course"]>

export type CourseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  description?: boolean
  language?: boolean
  level?: boolean
  status?: boolean
  thumbnail?: boolean
  coverImage?: boolean
  duration?: boolean
  lessonsCount?: boolean
  studentsCount?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
}, ExtArgs["result"]["course"]>

export type CourseSelectScalar = {
  id?: boolean
  slug?: boolean
  title?: boolean
  description?: boolean
  language?: boolean
  level?: boolean
  status?: boolean
  thumbnail?: boolean
  coverImage?: boolean
  duration?: boolean
  lessonsCount?: boolean
  studentsCount?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
}

export type CourseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "title" | "description" | "language" | "level" | "status" | "thumbnail" | "coverImage" | "duration" | "lessonsCount" | "studentsCount" | "metaTitle" | "metaDescription" | "order" | "createdAt" | "updatedAt" | "publishedAt", ExtArgs["result"]["course"]>
export type CourseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.Course$lessonsArgs<ExtArgs>
  enrollments?: boolean | Prisma.Course$enrollmentsArgs<ExtArgs>
  mockTests?: boolean | Prisma.Course$mockTestsArgs<ExtArgs>
  _count?: boolean | Prisma.CourseCountOutputTypeDefaultArgs<ExtArgs>
}
export type CourseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CourseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CoursePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Course"
  objects: {
    lessons: Prisma.$LessonPayload<ExtArgs>[]
    enrollments: Prisma.$EnrollmentPayload<ExtArgs>[]
    mockTests: Prisma.$MockTestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    slug: string
    title: string
    description: string
    language: string
    level: $Enums.LanguageLevel
    status: $Enums.CourseStatus
    thumbnail: string | null
    coverImage: string | null
    duration: number | null
    lessonsCount: number
    studentsCount: number
    metaTitle: string | null
    metaDescription: string | null
    order: number
    createdAt: Date
    updatedAt: Date
    publishedAt: Date | null
  }, ExtArgs["result"]["course"]>
  composites: {}
}

export type CourseGetPayload<S extends boolean | null | undefined | CourseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CoursePayload, S>

export type CourseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CourseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CourseCountAggregateInputType | true
  }

export interface CourseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Course'], meta: { name: 'Course' } }
  /**
   * Find zero or one Course that matches the filter.
   * @param {CourseFindUniqueArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CourseFindUniqueArgs>(args: Prisma.SelectSubset<T, CourseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Course that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CourseFindUniqueOrThrowArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CourseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CourseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Course that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseFindFirstArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CourseFindFirstArgs>(args?: Prisma.SelectSubset<T, CourseFindFirstArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Course that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseFindFirstOrThrowArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CourseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CourseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Courses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Courses
   * const courses = await prisma.course.findMany()
   * 
   * // Get first 10 Courses
   * const courses = await prisma.course.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const courseWithIdOnly = await prisma.course.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CourseFindManyArgs>(args?: Prisma.SelectSubset<T, CourseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Course.
   * @param {CourseCreateArgs} args - Arguments to create a Course.
   * @example
   * // Create one Course
   * const Course = await prisma.course.create({
   *   data: {
   *     // ... data to create a Course
   *   }
   * })
   * 
   */
  create<T extends CourseCreateArgs>(args: Prisma.SelectSubset<T, CourseCreateArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Courses.
   * @param {CourseCreateManyArgs} args - Arguments to create many Courses.
   * @example
   * // Create many Courses
   * const course = await prisma.course.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CourseCreateManyArgs>(args?: Prisma.SelectSubset<T, CourseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Courses and returns the data saved in the database.
   * @param {CourseCreateManyAndReturnArgs} args - Arguments to create many Courses.
   * @example
   * // Create many Courses
   * const course = await prisma.course.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Courses and only return the `id`
   * const courseWithIdOnly = await prisma.course.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CourseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CourseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Course.
   * @param {CourseDeleteArgs} args - Arguments to delete one Course.
   * @example
   * // Delete one Course
   * const Course = await prisma.course.delete({
   *   where: {
   *     // ... filter to delete one Course
   *   }
   * })
   * 
   */
  delete<T extends CourseDeleteArgs>(args: Prisma.SelectSubset<T, CourseDeleteArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Course.
   * @param {CourseUpdateArgs} args - Arguments to update one Course.
   * @example
   * // Update one Course
   * const course = await prisma.course.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CourseUpdateArgs>(args: Prisma.SelectSubset<T, CourseUpdateArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Courses.
   * @param {CourseDeleteManyArgs} args - Arguments to filter Courses to delete.
   * @example
   * // Delete a few Courses
   * const { count } = await prisma.course.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CourseDeleteManyArgs>(args?: Prisma.SelectSubset<T, CourseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Courses
   * const course = await prisma.course.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CourseUpdateManyArgs>(args: Prisma.SelectSubset<T, CourseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courses and returns the data updated in the database.
   * @param {CourseUpdateManyAndReturnArgs} args - Arguments to update many Courses.
   * @example
   * // Update many Courses
   * const course = await prisma.course.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Courses and only return the `id`
   * const courseWithIdOnly = await prisma.course.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CourseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CourseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Course.
   * @param {CourseUpsertArgs} args - Arguments to update or create a Course.
   * @example
   * // Update or create a Course
   * const course = await prisma.course.upsert({
   *   create: {
   *     // ... data to create a Course
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Course we want to update
   *   }
   * })
   */
  upsert<T extends CourseUpsertArgs>(args: Prisma.SelectSubset<T, CourseUpsertArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseCountArgs} args - Arguments to filter Courses to count.
   * @example
   * // Count the number of Courses
   * const count = await prisma.course.count({
   *   where: {
   *     // ... the filter for the Courses we want to count
   *   }
   * })
  **/
  count<T extends CourseCountArgs>(
    args?: Prisma.Subset<T, CourseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CourseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Course.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CourseAggregateArgs>(args: Prisma.Subset<T, CourseAggregateArgs>): Prisma.PrismaPromise<GetCourseAggregateType<T>>

  /**
   * Group by Course.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CourseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CourseGroupByArgs['orderBy'] }
      : { orderBy?: CourseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CourseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCourseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Course model
 */
readonly fields: CourseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Course.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CourseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.Course$lessonsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Course$lessonsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LessonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  enrollments<T extends Prisma.Course$enrollmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Course$enrollmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  mockTests<T extends Prisma.Course$mockTestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Course$mockTestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MockTestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Course model
 */
export interface CourseFieldRefs {
  readonly id: Prisma.FieldRef<"Course", 'String'>
  readonly slug: Prisma.FieldRef<"Course", 'String'>
  readonly title: Prisma.FieldRef<"Course", 'String'>
  readonly description: Prisma.FieldRef<"Course", 'String'>
  readonly language: Prisma.FieldRef<"Course", 'String'>
  readonly level: Prisma.FieldRef<"Course", 'LanguageLevel'>
  readonly status: Prisma.FieldRef<"Course", 'CourseStatus'>
  readonly thumbnail: Prisma.FieldRef<"Course", 'String'>
  readonly coverImage: Prisma.FieldRef<"Course", 'String'>
  readonly duration: Prisma.FieldRef<"Course", 'Int'>
  readonly lessonsCount: Prisma.FieldRef<"Course", 'Int'>
  readonly studentsCount: Prisma.FieldRef<"Course", 'Int'>
  readonly metaTitle: Prisma.FieldRef<"Course", 'String'>
  readonly metaDescription: Prisma.FieldRef<"Course", 'String'>
  readonly order: Prisma.FieldRef<"Course", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Course", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Course", 'DateTime'>
  readonly publishedAt: Prisma.FieldRef<"Course", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Course findUnique
 */
export type CourseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter, which Course to fetch.
   */
  where: Prisma.CourseWhereUniqueInput
}

/**
 * Course findUniqueOrThrow
 */
export type CourseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter, which Course to fetch.
   */
  where: Prisma.CourseWhereUniqueInput
}

/**
 * Course findFirst
 */
export type CourseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter, which Course to fetch.
   */
  where?: Prisma.CourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courses to fetch.
   */
  orderBy?: Prisma.CourseOrderByWithRelationInput | Prisma.CourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Courses.
   */
  cursor?: Prisma.CourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Courses.
   */
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * Course findFirstOrThrow
 */
export type CourseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter, which Course to fetch.
   */
  where?: Prisma.CourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courses to fetch.
   */
  orderBy?: Prisma.CourseOrderByWithRelationInput | Prisma.CourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Courses.
   */
  cursor?: Prisma.CourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Courses.
   */
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * Course findMany
 */
export type CourseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter, which Courses to fetch.
   */
  where?: Prisma.CourseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courses to fetch.
   */
  orderBy?: Prisma.CourseOrderByWithRelationInput | Prisma.CourseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Courses.
   */
  cursor?: Prisma.CourseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courses.
   */
  skip?: number
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * Course create
 */
export type CourseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * The data needed to create a Course.
   */
  data: Prisma.XOR<Prisma.CourseCreateInput, Prisma.CourseUncheckedCreateInput>
}

/**
 * Course createMany
 */
export type CourseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Courses.
   */
  data: Prisma.CourseCreateManyInput | Prisma.CourseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Course createManyAndReturn
 */
export type CourseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * The data used to create many Courses.
   */
  data: Prisma.CourseCreateManyInput | Prisma.CourseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Course update
 */
export type CourseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * The data needed to update a Course.
   */
  data: Prisma.XOR<Prisma.CourseUpdateInput, Prisma.CourseUncheckedUpdateInput>
  /**
   * Choose, which Course to update.
   */
  where: Prisma.CourseWhereUniqueInput
}

/**
 * Course updateMany
 */
export type CourseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Courses.
   */
  data: Prisma.XOR<Prisma.CourseUpdateManyMutationInput, Prisma.CourseUncheckedUpdateManyInput>
  /**
   * Filter which Courses to update
   */
  where?: Prisma.CourseWhereInput
  /**
   * Limit how many Courses to update.
   */
  limit?: number
}

/**
 * Course updateManyAndReturn
 */
export type CourseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * The data used to update Courses.
   */
  data: Prisma.XOR<Prisma.CourseUpdateManyMutationInput, Prisma.CourseUncheckedUpdateManyInput>
  /**
   * Filter which Courses to update
   */
  where?: Prisma.CourseWhereInput
  /**
   * Limit how many Courses to update.
   */
  limit?: number
}

/**
 * Course upsert
 */
export type CourseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * The filter to search for the Course to update in case it exists.
   */
  where: Prisma.CourseWhereUniqueInput
  /**
   * In case the Course found by the `where` argument doesn't exist, create a new Course with this data.
   */
  create: Prisma.XOR<Prisma.CourseCreateInput, Prisma.CourseUncheckedCreateInput>
  /**
   * In case the Course was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CourseUpdateInput, Prisma.CourseUncheckedUpdateInput>
}

/**
 * Course delete
 */
export type CourseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
  /**
   * Filter which Course to delete.
   */
  where: Prisma.CourseWhereUniqueInput
}

/**
 * Course deleteMany
 */
export type CourseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Courses to delete
   */
  where?: Prisma.CourseWhereInput
  /**
   * Limit how many Courses to delete.
   */
  limit?: number
}

/**
 * Course.lessons
 */
export type Course$lessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lesson
   */
  select?: Prisma.LessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lesson
   */
  omit?: Prisma.LessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonInclude<ExtArgs> | null
  where?: Prisma.LessonWhereInput
  orderBy?: Prisma.LessonOrderByWithRelationInput | Prisma.LessonOrderByWithRelationInput[]
  cursor?: Prisma.LessonWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * Course.enrollments
 */
export type Course$enrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Enrollment
   */
  select?: Prisma.EnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Enrollment
   */
  omit?: Prisma.EnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EnrollmentInclude<ExtArgs> | null
  where?: Prisma.EnrollmentWhereInput
  orderBy?: Prisma.EnrollmentOrderByWithRelationInput | Prisma.EnrollmentOrderByWithRelationInput[]
  cursor?: Prisma.EnrollmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EnrollmentScalarFieldEnum | Prisma.EnrollmentScalarFieldEnum[]
}

/**
 * Course.mockTests
 */
export type Course$mockTestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MockTest
   */
  select?: Prisma.MockTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MockTest
   */
  omit?: Prisma.MockTestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MockTestInclude<ExtArgs> | null
  where?: Prisma.MockTestWhereInput
  orderBy?: Prisma.MockTestOrderByWithRelationInput | Prisma.MockTestOrderByWithRelationInput[]
  cursor?: Prisma.MockTestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MockTestScalarFieldEnum | Prisma.MockTestScalarFieldEnum[]
}

/**
 * Course without action
 */
export type CourseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Course
   */
  select?: Prisma.CourseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Course
   */
  omit?: Prisma.CourseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseInclude<ExtArgs> | null
}
